#!/bin/bash
set -e

# Select disk
clear
echo WARNING: Back up data. The entire disk will be wiped.
PS3='Select disk: '
select disk in $(lsblk -do NAME -x SIZE | tac | head -n -2)
do [[ -n $disk ]] && break || echo Invalid selection. Try again.
done
[[ $disk =~ [0-9]$ ]] && separator=p

# Set credentials
clear
read -p 'Set username: ' username
read -p 'Set password: ' password

# Synchronize system clock
timedatectl set-ntp true

# Create partitions
parted -s /dev/$disk mklabel gpt mkpart ESP fat32 1MiB 1025MiB set 1 esp on mkpart ARCH 1025MiB 100%

# Format ESP partition
mkfs.fat -F32 /dev/$disk$separator'1'

# Format root partition
# mkfs.bcachefs -f --compression=zstd --discard /dev/$disk$separator'2'
bcachefs format -f --compression=zstd --discard /dev/$disk$separator'2'

# Mount root partition
# mount -o noatime -t bcachefs /dev/$disk$separator'2' /mnt
bcachefs mount -o noatime /dev/$disk$separator'2' /mnt

# Mount ESP partition
mount -o umask=0077 -m /dev/$disk$separator'1' /mnt/boot

cp /etc/pacman-more.conf /etc/pacman.conf
sed -i 's/\(ParallelDownloads = \)10$/\1'$[`nproc`-1]'/' /etc/pacman.conf
sed -i 's/#<disabled_v3>//g' /etc/pacman.conf

pacstrap -K /mnt base bluez booster cachyos-keyring cachyos-mirrorlist cachyos-rate-mirrors cachyos-v3-mirrorlist cuda dbus-broker-units firefox firefox-ublock-origin fuzzel helix iptables-nft keepassxc libva-mesa-driver libva-nvidia-driver linux-cachyos linux-cachyos-nvidia-open linux-firmware logrotate ly mesa-vdpau networkmanager niri noto-fonts noto-fonts-cjk noto-fonts-emoji obs-studio openconnect pipewire-alsa pipewire-jack qt6-wayland sbctl systemd-resolvconf vulkan-radeon wgcf wireguard-tools xdg-desktop-portal-gnome zed zram-generator

#aria2 cups distrobox podman typst espeak-ng fwupd hunspell hunspell-en_us hyphen hyphen-en libmythes libreoffice-fresh mythes-en opencl-rusticl-mesa rocm-opencl-runtime pipewire-pulse netctl systemd-boot-manager
#dosfstools e2fsprogs exfatprogs f2fs-tools jfsutils sysfsutils usbutils xfsprogs cosmic-session-git

genfstab -U /mnt > /mnt/etc/fstab

arch-chroot /mnt <<EOF

ln -s /usr/share/zoneinfo/$(curl https://ipapi.co/timezone) /etc/localtime
hwclock -wu

sed -i 's/#\(en_US.UTF-8 UTF-8\)/\1/' /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf

echo host > /etc/hostname

useradd -mG wheel $username
echo $username:$password | chpasswd

yes | wgcf register
wgcf generate
cp wgcf-profile.conf /etc/wireguard
rm wgcf-account.toml wgcf-profile.conf

systemctl enable bluetooth ly NetworkManager nftables systemd-resolved systemd-timesyncd wg-quick@wgcf-profile

mkdir -p /boot/loader/entries
echo 'title Linux
linux /vmlinuz-linux-cachyos
initrd /booster-linux-cachyos.img
options root=PARTLABEL=ARCH rw rootfstype=bcachefs lockdown=integrity zswap.enabled=0 nowatchdog nouveau.config=NvGspRm=1' > /boot/loader/entries/linux.conf

mkdir /etc/pacman.d/hooks
echo '[Trigger]
Type = Package
Operation = Upgrade
Target = systemd
[Action]
Description = Upgrading systemd-boot...
When = PostTransaction
Exec = systemctl restart systemd-boot-update' > /etc/pacman.d/hooks/1-systemd-boot.hook

bootctl install

echo '[zram0]
zram-size = ram
compression-algorithm = zstd' > /etc/systemd/zram-generator.conf

sbctl create-keys
sbctl enroll-keys -m
sbctl sign -s /boot/EFI/BOOT/BOOTX64.EFI
sbctl sign -s /boot/EFI/systemd/systemd-bootx64.efi
sbctl sign -s /boot/vmlinuz-linux-cachyos

EOF

umount -lR /mnt
reboot
