#!/usr/bin/env sh

cd ~
echo 'SUBSYSTEM=="block", ENV{ID_FS_TYPE}=="ntfs", ENV{ID_FS_TYPE}="ntfs3"' | sudo tee /etc/udev/rules.d/ntfs3_by_default.rules
sudo sed -i "s/^#ParallelDownloads = 5$/ParallelDownloads = 36/" /etc/pacman.conf

# fonts
sudo pacman -Syu noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra
# tools
sudo pacman -Syu git wget curl fzf helix imagemagick ffmpeg bluez bluez-utils fwupd mpv meld cups cups-pdf
# applications
sudo pacman -Syu qbittorrent libreoffice-fresh hunspell-en_us lapce obs-studio

sudo pacman -Syu --needed base-devel
git clone https://aur.archlinux.org/paru-bin.git
cd paru-bin
makepkg -si
cd ..
rm -rf paru-bin

# fonts
paru -Syu apple-fonts ttf-ms-win11-auto
# tools
paru -Syu fastfetch cloudflare-warp-bin ventoy-bin brave-bin

# enable GNOME Wayland on NVIDIA GPU
sudo ln -s /dev/null /etc/udev/rules.d/61-gdm.rules
# asus tools
paru -Syu asusctl supergfxctl
# enable asus tools
systemctl enable --now power-profiles-daemon
systemctl enable --now supergfxd

systemctl enable --now nftables
systemctl enable --now bluetooth
systemctl enable --now warp-svc
systemctl enable --now cups.socket

yes | warp-cli register
warp-cli set-families-mode malware
warp-cli set-mode warp
paru
