#!/usr/bin/env sh
cd ~

alias ri = 'yes | flatpak install flathub'

# play and record videos
ri io.github.celluloid_player.Celluloid com.github.rafostar.Clapper com.obsproject.Studio

# applications
ri io.gitlab.librewolf-community com.brave.Browser org.libreoffice.LibreOffice org.qbittorrent.qBittorrent dev.lapce.lapce

# games
# NOTE: cemu and desmume are not included as they have no and outdated Flatpaks, respectively
ri com.usebottles.bottles com.valvesoftware.Steam org.ryujinx.Ryujinx org.yuzu_emu.yuzu org.citra_emu.citra org.DolphinEmu.dolphin-emu

# graphics
ri org.blender.Blender org.gimp.GIMP org.inkscape.Inkscape

curl https://raw.githubusercontent.com/kojq/run/main/microOS | sh
