#!/usr/bin/env sh

cd ~
#graphics
sudo pacman -S blender inkscape gimp
#coding
paru -S visual-studio-code-bin jetbrains-fleet
#misc
sudo pacman -S pandoc-bin linux-wifi-hotspot

#virtual machine
sudo pacman -S virt-manager qemu-desktop libvirt edk2-ovmf dnsmasq iptables-nft
systemctl enable --now libvirtd

#kitty pcmanfm refind booster borg bupstash restic
#librewolf-bin fprintd btrbk kopia-bin vorta pika-backup backintime rog-control-center ulauncher tofi kickoff/wofi/fuzzel/bemenu

#set ChangeFanProfile, fn+f5 to asusctl profile -n
#set fn+f4, fn+f6, ROG Key, and ctrl+shift+delete
