#!/usr/bin/env sh

cd ~
sudo pacman -S desmume dolphin-emu
paru -S cemu citra-qt-bin yuzu-mainline-bin ryujinx-git
flatpak install flathub com.valvesoftware.Steam

#sudo sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf
#sudo pacman -S lib32-nvidia-utils lib32-vulkan-radeon steam
