#!/bin/bash
set -e

# Select disk
clear
echo WARNING: Back up data. The entire disk will be wiped.
PS3='Select disk: '
select disk in $(lsblk -do NAME -x SIZE | tac | head -n -2)
do [[ -n $disk ]] && break || echo Invalid selection. Try again.
done
[[ $disk =~ [0-9]$ ]] && separator=p

# Set credentials
clear
read -p 'Set username: ' username
read -p 'Set password: ' password

# Synchronize system clock
timedatectl set-ntp true

# Create partitions
parted -s /dev/$disk mklabel gpt mkpart ESP fat32 1MiB 1025MiB set 1 esp on mkpart ARCH 1025MiB 100%

# Format ESP partition
mkfs.fat -F32 /dev/$disk$separator'1'

# Format root partition
# mkfs.bcachefs -f --compression=zstd:4 --discard --encrypted /dev/$disk$separator'2'
bcachefs format -f --compression=zstd:4 --discard /dev/$disk$separator'2'

# Unlock root partition (-k session)?
# bcachefs unlock /dev/$disk$separator'2'

# Mount root partition
# mount -o noatime -t bcachefs /dev/$disk$separator'2' /mnt
bcachefs mount -o noatime /dev/$disk$separator'2' /mnt

# Mount ESP partition
mount -o umask=0077 -m /dev/$disk$separator'1' /mnt/boot

cp /etc/pacman-more.conf /etc/pacman.conf
sed -i 's/\(ParallelDownloads = \)10$/\1'$[`nproc`-1]'/' /etc/pacman.conf
sed -i 's/#<disabled_v3>//g' /etc/pacman.conf
sed -i '/\[multilib\]/,+1 s/^/#/' /etc/pacman.conf

pacstrap -K /mnt apparmor base bluez booster cachyos-keyring cachyos-mirrorlist cachyos-v3-mirrorlist cosmic-files cosmic-session cuda cups-pdf dbus-broker-units espeak-ng firefox-developer-edition helix iptables-nft keepassxc libva-mesa-driver linux-cachyos-lto linux-cachyos-lto-nvidia-open linux-firmware logrotate mesa-vdpau networkmanager noto-fonts noto-fonts-cjk noto-fonts-emoji obs-studio openconnect pipewire-alsa pipewire-jack pipewire-pulse qt6-wayland sbctl speech-dispatcher system76-power systemd-resolvconf upower vulkan-radeon wgcf wireguard-tools xdg-user-dirs zed zram-generator

#fcitx5-configtool fcitx5-hangul fcitx5-libthai fcitx5-mozc fcitx5-sayura fcitx5-unikey
#fcitx5-chewing fcitx5-m17n fcitx5-pinyin-zhwiki fcitx5-table-other
#aria2 hunspell hunspell-en_us hyphen hyphen-en libmythes libreoffice-fresh mythes-en opencl-rusticl-mesa pijul rocm-opencl-runtime typst

genfstab -U /mnt > /mnt/etc/fstab

arch-chroot /mnt <<EOF

curl -o /etc/pacman.conf https://raw.githubusercontent.com/kojq/gal/main/pacman.conf

ln -s /usr/share/zoneinfo/$(curl https://ipapi.co/timezone) /etc/localtime
hwclock -wu

sed -i 's/#\(en_US.UTF-8 UTF-8\)/\1/' /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
echo host > /etc/hostname

useradd -mG wheel $username
echo $username:$password | chpasswd

yes | wgcf register
wgcf generate
cp wgcf-profile.conf /etc/wireguard
rm wgcf-account.toml wgcf-profile.conf
sed -i '/^DNS/ s/.\{1\}$/2/' /etc/wireguard/wgcf-profile.conf

systemctl enable apparmor bluetooth com.system76.PowerDaemon cosmic-greeter cups.socket NetworkManager nftables systemd-resolved systemd-timesyncd upower wg-quick@wgcf-profile

mkdir -p /boot/loader/entries
echo 'title Linux
linux /vmlinuz-linux-cachyos-lto
initrd /booster-linux-cachyos-lto.img
options lsm=landlock,lockdown,yama,integrity,apparmor,bpf nouveau.config=NvGspRm=1 nowatchdog nvidia_drm.fbdev=1 nvidia_drm.modeset=1 quiet root=PARTLABEL=ARCH rootfstype=bcachefs rw zswap.enabled=0' > /boot/loader/entries/linux.conf

mkdir /etc/pacman.d/hooks
echo '[Trigger]
Type = Package
Operation = Upgrade
Target = systemd
[Action]
Description = Upgrading systemd-boot...
When = PostTransaction
Exec = /usr/bin/systemctl restart systemd-boot-update' > /etc/pacman.d/hooks/1-systemd-boot.hook

bootctl install

echo '[zram0]
zram-size = ram
compression-algorithm = zstd' > /etc/systemd/zram-generator.conf

sbctl create-keys
sbctl enroll-keys -m
sbctl sign -s /boot/EFI/BOOT/BOOTX64.EFI
sbctl sign -s /boot/EFI/systemd/systemd-bootx64.efi
sbctl sign -s /boot/vmlinuz-linux-cachyos-lto

EOF

umount -lR /mnt
reboot
