#!/bin/sh
set -e

# Set account credentials
read -p "Set the account username: " username
read -s -p "Set the account password: " password
read -s -p "Set the root password: " root_password

# Synchronize the system clock
timedatectl set-ntp true

# Create partitions
parted -s /dev/nvme0n1 mklabel gpt
parted /dev/nvme0n1 mkpart ESP fat32 1MiB 513MiB
parted /dev/nvme0n1 set 1 esp on
parted /dev/nvme0n1 mkpart ARCH btrfs 513MiB 100%

# Format partitions
mkfs.fat -F32 /dev/nvme0n1p1
mkfs.btrfs -f /dev/nvme0n1p2

# Mount the root partition
mount /dev/nvme0n1p2 /mnt

# Create subvolumes
btrfs su c /mnt/root
btrfs su c /mnt/home
btrfs su c /mnt/snapshots

# Unmount the root partition
umount /mnt

# Mount the root subvolume
mount -o noatime,compress=zstd,subvol=root /dev/nvme0n1p2 /mnt

# Mount the home subvolume
mkdir /mnt/home
mount -o noatime,compress=zstd,subvol=home /dev/nvme0n1p2 /mnt/home

# Mount the snapshots subvolume
mkdir /mnt/.snapshots
mount -o noatime,compress=zstd,subvol=snapshots /dev/nvme0n1p2 /mnt/.snapshots

# Mount the ESP partition
mkdir /mnt/boot
mount /dev/nvme0n1p1 /mnt/boot

pacstrap -Ki /mnt amd-ucode aria2 baobab base base-devel booster bottom btrfs-progs cups distrobox eog espeak-ng evince firefox firefox-ublock-origin fprintd fwupd gdm git gnome-backgrounds gnome-calculator gnome-calendar gnome-characters gnome-clocks gnome-console gnome-control-center gnome-disk-utility gnome-font-viewer gnome-keyring gnome-logs gnome-sound-recorder gnome-system-monitor gnome-user-share gnome-weather gvfs gvfs-afc gvfs-goa gvfs-google gvfs-gphoto2 gvfs-mtp gvfs-nfs gvfs-smb helix hunspell hunspell-en_us hyphen hyphen-en imagemagick intel-media-driver intel-ucode lapce libmythes libreoffice-fresh libva-mesa-driver linux linux-firmware mesa mesa-vdpau mpv mythes-en nautilus networkmanager nftables noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra nvidia obs-studio orca pipewire pipewire-jack podman qt6-wayland reflector sbctl simple-scan skim tectonic vulkan-intel vulkan-radeon wireplumber xdg-desktop-portal-gnome zram-generator

genfstab -U /mnt > /mnt/etc/fstab

arch-chroot /mnt /bin/sh <<EOF

ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime
hwclock -wu

sed -i 's/#\(en_US.UTF-8 UTF-8\)/\1/' /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf

echo arch > /etc/hostname
echo '127.0.0.1 localhost
::1 localhost
127.0.1.1 arch.localdomain arch' > /etc/hosts

sed -i -E 's/^#(Color|VerbosePkgLists)$/\1/' /etc/pacman.conf
sed -i 's/^#\(ParallelDownloads = \)5$/\1'$[`nproc`-1]'/' /etc/pacman.conf

echo '
export EDITOR=/usr/bin/helix' >> /etc/bash.bashrc

systemctl enable bluetooth cups.socket gdm NetworkManager nftables reflector.timer systemd-timesyncd

useradd -mG wheel $username
echo $username:$password | chpasswd
echo root:$root_password | chpasswd
echo $username 'ALL=(ALL) ALL' > /etc/sudoers.d/owners

mkdir /etc/pacman.d/hooks/

echo '[Trigger]
Type = Package
Operation = Upgrade
Target = systemd

[Action]
Description = Gracefully upgrading systemd-boot...
When = PostTransaction
Exec = /usr/bin/systemctl restart systemd-boot-update' > /etc/pacman.d/hooks/95-systemd-boot.hook

mkdir -p /boot/loader/entries/

echo 'title Arch Linux
linux /vmlinuz-linux
initrd /amd-ucode.img
initrd /intel-ucode.img
initrd /booster-linux.img
options root=PARTLABEL=ARCH zswap.enabled=0 rootflags=subvol=root rootfstype=btrfs rw' > /boot/loader/entries/arch.conf

bootctl install

echo '[zram0]
zram-size = ram / 2
compression-algorithm = zstd
swap-priority = 100
fs-type = swap' > /etc/systemd/zram-generator.conf
systemctl start systemd-zram-setup@zram0

sbctl create-keys
sbctl enroll-keys -m
sbctl sign -s /boot/EFI/BOOT/BOOTX64.EFI
sbctl sign -s /boot/EFI/systemd/systemd-bootx64.efi
sbctl sign -s /boot/vmlinuz-linux

touch /etc/udev/rules.d/61-gdm.rules

EOF

umount -R /mnt
reboot

# Features I have not had the opportunity to include:

#dbus-launch gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true

#git clone https://aur.archlinux.org/paru-bin.git
#cd paru-bin
#makepkg -si
#cd ..
#rm -rf paru-bin

#paru -Syu cloudflare-warp-bin
#yes|warp-cli register
#warp-cli set-families-mode malware
#warp-cli connect
#systemctl enable --now warp-svc

#pacman-key -r 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35
#pacman-key --lsign-key 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35
#grep g14 /etc/pacman.conf || echo -e '\n[g14]\nServer = https://arch.asus-linux.org' | sudo tee -a /etc/pacman.conf
#pacman -Syu --noconfirm --needed asusctl
#systemctl enable --now power-profiles-daemon
