#!/usr/bin/env sh
cd ~

PS3="Enter a number: "
select distro in Arch MicroOS
do
    echo "$distro was chosen."
    sh <(curl https://raw.githubusercontent.com/kojq/run/main/distributions/$distro)
    break
done
sh <(curl https://raw.githubusercontent.com/kojq/run/main/Flatpaks)
