#!/usr/bin/env sh

PS3='> '
select choice in 'core' 'game' 'extra'
do
case $REPLY in
    1) sh <(curl https://raw.githubusercontent.com/kojq/run/main/$choice);;
    2) sh <(curl https://raw.githubusercontent.com/kojq/run/main/$choice);;
    3) sh <(curl https://raw.githubusercontent.com/kojq/run/main/$choice);;
esac
done
