#!/usr/bin/env sh
cd ~

# enable GNOME Wayland due to proprietary NVIDIA drivers (THIS MIGHT GO TO "core" AFTER TESTING ON openSUSE)
sudo ln -s /dev/null /etc/udev/rules.d/61-gdm.rules
# mount and unmount NTFS drives
echo "SUBSYSTEM=='block', ENV{ID_FS_TYPE}=='ntfs', ENV{ID_FS_TYPE}='ntfs3'" | sudo tee /etc/udev/rules.d/ntfs3_by_default.rules
# enable parallel downloads
sudo sed -i 's/^#ParallelDownloads = 5$/ParallelDownloads = 36/' /etc/pacman.conf

# AUR helper
sudo pacman -Syu --noconfirm --needed base-devel
git clone https://aur.archlinux.org/paru-bin.git
cd paru-bin
yes | makepkg -si
cd ..
rm -rf paru-bin

# fonts
sudo pacman -Syu --noconfirm noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra
paru -Syu --noconfirm apple-fonts ttf-ms-win11-auto

# tools
sudo pacman -Syu --noconfirm bluez bluez-utils cups cups-pdf curl ffmpeg fwupd fzf git helix imagemagick wget
paru -Syu --noconfirm fastfetch cloudflare-warp-bin ventoy-bin gnome-shell-extension-blur-my-shell game-devices-udev

# enable services
sudo systemctl enable --now nftables bluetooth warp-svc cups.socket
yes | warp-cli register
warp-cli set-families-mode malware
warp-cli set-mode warp

# asus tools
paru -Syu --noconfirm supergfxctl asusctl
sudo systemctl enable --now power-profiles-daemon supergfxd
