#!/usr/bin/env sh
cd ~

# enable GNOME Wayland due to proprietary NVIDIA drivers
sudo touch /etc/udev/rules.d/61-gdm.rules
# enable recognition of NTFS drives
echo 'SUBSYSTEM=="block", ENV{ID_FS_TYPE}=="ntfs", ENV{ID_FS_TYPE}="ntfs3"' | sudo tee /etc/udev/rules.d/ntfs3_by_default.rules
# enable parallel downloads
sudo sed -i 's/^#ParallelDownloads = 5$/ParallelDownloads = 30/' /etc/pacman.conf
sudo sed -i 's/^#Color$/Color/' /etc/pacman.conf
sudo sed -i 's/^#VerbosePkgLists$/VerbosePkgLists/' /etc/pacman.conf

# AUR helper
sudo pacman -Syu --noconfirm --needed base-devel
git clone https://aur.archlinux.org/paru-bin.git
cd paru-bin
makepkg -si --noconfirm --needed
cd ..
rm -rf paru-bin

# fonts
sudo pacman -Syu --noconfirm --needed noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra
paru -Syu --noconfirm --needed ttf-ms-win11-auto apple-fonts

# tools
sudo pacman -Syu --noconfirm --needed bluez bluez-utils cups cups-pdf fwupd sbctl
sudo pacman -Syu --noconfirm --needed fzf git imagemagick podman
paru -Syu --noconfirm --needed game-devices-udev distrobox fastfetch cloudflare-warp-bin ventoy-bin gdm-settings systemd-boot-pacman-hook

# enable services
sudo systemctl enable --now nftables bluetooth warp-svc cups.socket
y | warp-cli register
warp-cli set-families-mode malware

# ROG tools
grep g14 /etc/pacman.conf || echo -e '\n[g14]\nServer = https://arch.asus-linux.org' | sudo tee -a /etc/pacman.conf
sudo pacman -Syu --noconfirm --needed asusctl supergfxctl
sudo systemctl enable --now power-profiles-daemon supergfxd

# virtual machine
# sudo pacman -Syu virt-manager qemu-desktop libvirt edk2-ovmf dnsmasq iptables-nft
# sudo systemctl enable --now libvirtd

# enable multilib
# sudo sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf

# kitty pcmanfm refind borg bupstash restic
# pandoc-bin fprintd jetbrains-fleet btrbk kopia-bin vorta pika-backup backintime ulauncher tofi kickoff/wofi/fuzzel/bemenu
