#!/usr/bin/env sh
cd ~

# enable GNOME Wayland due to proprietary NVIDIA drivers
sudo touch /etc/udev/rules.d/61-gdm.rules
# enable recognition of NTFS drives
echo 'SUBSYSTEM=="block", ENV{ID_FS_TYPE}=="ntfs", ENV{ID_FS_TYPE}="ntfs3"' | sudo tee /etc/udev/rules.d/ntfs3_by_default.rules
# enable parallel downloads
sudo sed -i 's/^#ParallelDownloads = 5$/ParallelDownloads = 36/' /etc/pacman.conf

# AUR helper
sudo pacman -Syu --noconfirm --needed base-devel
git clone https://aur.archlinux.org/paru-bin.git
cd paru-bin
yes | makepkg -si
cd ..
rm -rf paru-bin

# fonts
sudo pacman -Syu --noconfirm noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra
paru -Syu --noconfirm ttf-ms-win11-auto apple-fonts

# tools
sudo pacman -Syu --noconfirm bluez bluez-utils cups cups-pdf fwupd
sudo pacman -Syu --noconfirm ffmpeg fzf git helix imagemagick
paru -Syu --noconfirm game-devices-udev distrobox fastfetch cloudflare-warp-bin ventoy-bin gdm-settings

# enable services
sudo systemctl enable --now nftables bluetooth warp-svc cups.socket
yes | warp-cli register
warp-cli set-families-mode malware
warp-cli set-mode warp

# ROG tools
grep g14 /etc/pacman.conf || echo -e '\n[g14]\nSigLevel = DatabaseNever Optional TrustAll\nServer = https://arch.asus-linux.org' | sudo tee -a /etc/pacman.conf
paru -Syu --noconfirm asusctl supergfxctl
sudo systemctl enable --now power-profiles-daemon supergfxd
# strange behavior so it is commented for now
# sudo systemctl disable --now nvidia-powerd

# virtual machine
# sudo pacman -Syu virt-manager qemu-desktop libvirt edk2-ovmf dnsmasq iptables-nft
# sudo systemctl enable --now libvirtd

# kitty pcmanfm refind booster borg bupstash restic
# pandoc-bin jetbrains-fleet fprintd btrbk kopia-bin vorta pika-backup backintime ulauncher tofi kickoff/wofi/fuzzel/bemenu

# installs Steam with NVIDIA and AMD utils
# sudo sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf
# sudo pacman -Syu lib32-nvidia-utils lib32-vulkan-radeon steam
