#!/usr/bin/env sh
cd ~

# console can replace terminal
sudo transactional-update -n -c pkg rm gnome-terminal

# drivers
# sudo sed -i 's/^multiversion =$/multiversion = provides:multiversion(kernel)/' /etc/zypp/zypp.conf
sudo transactional-update -n -c pkg in kernel-firmware-nvidia
sudo zypper ar -f https://download.nvidia.com/opensuse/tumbleweed NVIDIA
sudo transactional-update -n -c pkg in x11-video-nvidiaG06 nvidia-glG06

# tools
sudo transactional-update -n -c pkg in console fzf git helix ImageMagick steam-devices
# sudo transactional-update -n -c pkg in virt-manager libvirt qemu libvirt-daemon-driver-qemu qemu-kvm
# sudo systemctl enable --now libvirtd
# from Arch: edk2-ovmf dnsmasq iptables-nft

# asus tools
# sudo zypper ar -f https://download.opensuse.org/repositories/home:/luke_nukem:/asus/openSUSE_Tumbleweed/ asus-linux
# sudo transactional-update -n -c pkg in asusctl supergfxctl
# sudo systemctl enable --now power-profiles-daemon supergfxd

# below is a WIP
# jetbrains-fleet pandoc
# noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra apple-fonts ttf-ms-win11-auto
# fastfetch cloudflare-warp-bin ventoy-bin
# sudo systemctl enable --now nftables warp-svc
# yes | warp-cli register
# warp-cli set-families-mode malware
# warp-cli set-mode warp
